import { DatabaseDecorators } from "@backend/database/decorators";
import { DatabaseBase } from "@backend/database/model/database.base";
import { DevicePlatform } from "@backend/user/model/user.device.type";
import { User } from "@backend/user/model/user.model";
import { ApiHideProperty } from "@nestjs/swagger";
import { Exclude } from "class-transformer";
import { IsEnum } from "class-validator";
import { ManyToOne } from "typeorm";

/** This class tracks individual devices registered to a specific user */
@DatabaseDecorators.entity()
export class UserDevice extends DatabaseBase {
  /** A required device ID that will be provided by the device. This will be unique. */
  @DatabaseDecorators.column({ nullable: false, unique: false })
  deviceId: string;

  /** The unique FCM token generated by the device. Used for notifications, if permission was granted. If this is null, permissions were not granted */
  @DatabaseDecorators.column({ nullable: true, type: "varchar" })
  fcmToken: string | undefined;

  /** A friendly name for the device */
  @DatabaseDecorators.column({ nullable: true })
  deviceName?: string;

  /** Track the platform to handle specific payload requirements later */
  @DatabaseDecorators.column({
    type: "varchar",
    default: DevicePlatform.ANDROID,
  })
  @IsEnum(DevicePlatform)
  platform: DevicePlatform;

  /** The date this device was last seen/registered from a connection */
  @DatabaseDecorators.column({ nullable: false })
  lastSeenAt: Date = new Date();

  /** The user this device belongs to */
  @ManyToOne(() => User, (u) => u.id, { onDelete: "CASCADE" })
  @ApiHideProperty()
  @Exclude()
  user: User;

  constructor(user: User, deviceId: string, fcmToken: string | undefined, platform: DevicePlatform, deviceName?: string) {
    super();
    this.user = user;
    this.deviceId = deviceId;
    this.fcmToken = fcmToken;
    this.platform = platform;
    this.deviceName = deviceName;
  }
}
