import 'package:sprout/transaction/models/transaction.dart';

/// Contains stats generated by the cash flow math
class CashFlowStats {
  final double totalExpense;
  final double totalIncome;

  /// How many total transactions we have for this query
  final int count;

  /// The largest expense we had for this time period
  final Transaction? largestExpense;

  CashFlowStats({
    required this.totalExpense,
    required this.totalIncome,
    required this.count,
    required this.largestExpense,
  });

  factory CashFlowStats.fromJson(Map<String, dynamic> json) {
    return CashFlowStats(
      totalExpense: (json['totalExpense'] as num).toDouble(),
      totalIncome: (json['totalIncome'] as num).toDouble(),
      count: json['count'] as int,
      largestExpense: json['largestExpense'] != null ? Transaction.fromJson(json['largestExpense']) : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {'totalExpense': totalExpense, 'totalIncome': totalIncome, 'count': count, 'largestExpense': largestExpense};
  }
}
