import { Base } from "@backend/core/model/base";
import { Transaction } from "@backend/transaction/model/transaction.model";

/** Contains stats generated by the cash flow math */
export class CashFlowStats extends Base {
  totalExpense: number;
  totalIncome: number;
  /** How many total transactions we have for this query */
  count: number;
  /** The largest expense we had for this time period */
  largestExpense?: Transaction;

  constructor(totalExpense: number, totalIncome: number, count: number, largestExpense?: Transaction) {
    super();
    this.totalExpense = totalExpense;
    this.totalIncome = totalIncome;
    this.count = count;
    this.largestExpense = largestExpense;
  }
}
