import { StrategyGuard } from "@backend/auth/guard/strategy.guard";
import { MobileTokenExchangeDto } from "@backend/auth/model/api/mobile.cookie.exchange.dto";
import { OIDCTokens } from "@backend/auth/model/oidc.tokens";
import { Configuration } from "@backend/config/core";
import { PublicURL } from "@backend/core/decorator/public.url.decorator";
import { HttpService } from "@nestjs/axios";
import { CACHE_MANAGER, Cache } from "@nestjs/cache-manager";
import { BadRequestException, Body, Controller, Get, HttpCode, HttpStatus, Inject, Logger, Put, Query, Req, Res, UnauthorizedException } from "@nestjs/common";
import { ApiOperation, ApiQuery, ApiResponse, ApiTags } from "@nestjs/swagger";
import { createHash, randomBytes } from "crypto";
import { Request, Response } from "express";
import { firstValueFrom } from "rxjs";
import { AuthService } from "./auth.service";

/** This controller provides the related to OIDC specific authentication. */
@Controller("auth/oidc")
@ApiTags("Auth")
@StrategyGuard.attach("oidc")
export class OIDCController {
  private readonly logger = new Logger("controller:auth:oidc");

  constructor(
    private readonly authService: AuthService,
    private readonly httpService: HttpService,
    @Inject(CACHE_MANAGER) private cacheManager: Cache,
  ) {}

  /**
   * Sets the access/id/refresh tokens into the cache so the mobile handoff can expand on them.
   * @param lifetime How long to let the tokens live in the cache before expiring them
   * @returns The handoff code to be able to access the tokens with that code, within that time frame.
   */
  private async setMobileHandoff(tokens: OIDCTokens, lifetime = 30000) {
    const handoffCode = randomBytes(32).toString("hex");
    await this.cacheManager.set(`handoff:${handoffCode}`, tokens, lifetime);
    return handoffCode;
  }

  /** Given a handoff code from mobile, retrieves the tokens and immediately burns them */
  private async getMobileHandoff(handoffCode: string) {
    const key = `handoff:${handoffCode}`;
    const tokens = await this.cacheManager.get<OIDCTokens>(key);
    if (!tokens) throw new UnauthorizedException("Invalid or expired exchange code");
    await this.cacheManager.del(key);
    return tokens;
  }

  @Get("login")
  @ApiOperation({
    summary: "Authenticates using the OIDC configuration.",
    description:
      "Authenticates to our OIDC server that is configured and handles redirecting the authentication capability back to API to complete the login request.",
  })
  @ApiQuery({
    name: "target_url",
    type: String,
    required: true,
    description:
      "The destination URL or mobile scheme to redirect to after successful authentication. Must be a registered public URL or allowed mobile scheme.",
  })
  @ApiQuery({
    name: "app_challenge",
    type: String,
    required: false,
    description:
      "A base64url-encoded SHA-256 hash of a secret verifier string generated by the requesting client. Used to cryptographically bind the login request to the final token exchange to prevent interception attacks.",
  })
  async loginOIDC(@Query("target_url") targetUrl: string, @Query("app_challenge") appChallenge: string, @Res() res: Response, @PublicURL() publicUrl: string) {
    // Ensure the target URL is either a relative path, matches our public URL, or is the allowed mobile scheme
    if (!this.authService.isValidRedirectUrl(targetUrl, publicUrl)) throw new BadRequestException("Invalid target URL provided.");

    const { issuer, clientId } = Configuration.server.auth.oidc;
    const redirectUri = `${publicUrl}${Configuration.server.basePath}/auth/oidc/callback`;
    // Security state
    const state = randomBytes(16).toString("hex");
    const codeVerifier = randomBytes(32).toString("base64url");
    const codeChallenge = createHash("sha256").update(codeVerifier).digest("base64url");
    // Store security configuration into a cookie
    res.cookie("oidc_pending", JSON.stringify({ state, codeVerifier, targetUrl, redirectUri, appChallenge }), {
      httpOnly: true,
      signed: true,
      secure: !Configuration.isDevBuild,
      maxAge: 5 * 60000, // 5 Minutes
    });

    // Create the params that contain all of the information for our authentication challenge
    const params = new URLSearchParams({
      client_id: clientId,
      response_type: "code",
      redirect_uri: redirectUri,
      scope: Configuration.server.auth.oidc.scopes.join(" "),
      state: state,
      code_challenge: codeChallenge,
      code_challenge_method: "S256",
    });

    return res.redirect(`${issuer}/api/oidc/authorization?${params.toString()}`);
  }

  @Get("callback")
  @ApiOperation({
    summary: "Callback handler for the OIDC login.",
    description: "Handles the redirect back from the OIDC server and handles state control to get the authentication response back to the original requester.",
  })
  async loginCallbackOIDC(
    @Query("code") code: string,
    @Query("state") state: string,
    @Req() req: Request,
    @Res() res: Response,
    @PublicURL() publicUrl: string,
  ) {
    const { issuer, authHeader } = Configuration.server.auth.oidc;

    // Validate Cookie
    const pendingCookie = req.signedCookies["oidc_pending"];
    if (!pendingCookie) throw new UnauthorizedException("Session expired");

    const { state: storedState, codeVerifier, targetUrl, redirectUri, appChallenge } = JSON.parse(pendingCookie);
    if (state !== storedState) throw new UnauthorizedException("State mismatch");

    try {
      // Exchange Code for Tokens
      const response = await firstValueFrom(
        this.httpService.post(
          `${issuer}/api/oidc/token`,
          new URLSearchParams({
            grant_type: "authorization_code",
            code: code,
            redirect_uri: redirectUri,
            code_verifier: codeVerifier,
          }).toString(),
          { headers: { "Content-Type": "application/x-www-form-urlencoded", Authorization: `Basic ${authHeader}` } },
        ),
      );

      const { id_token, access_token, refresh_token } = response.data;
      // Clear the temporary cookie
      res.clearCookie("oidc_pending");

      // We validate again to ensure the cookie wasn't tampered with (though it is signed) or that the logic hasn't drifted.
      if (!this.authService.isValidRedirectUrl(targetUrl, publicUrl)) {
        this.logger.warn(`Open redirect attempt detected to: ${targetUrl}`);
        throw new UnauthorizedException("Invalid redirect target");
      }

      const isMobileScheme = targetUrl.startsWith(AuthService.ALLOWED_MOBILE_SCHEME);
      if (isMobileScheme) {
        // For mobile, we pass a code back so they can exchange the code for their access credentials for their cookie jar.
        const code = await this.setMobileHandoff(new OIDCTokens(id_token, access_token, refresh_token, appChallenge));

        // Build the URL returning the handoff code so we can access them
        const redirectUrl = new URL(targetUrl);
        redirectUrl.searchParams.set("code", code);
        return res.redirect(redirectUrl.toString());
      } else {
        // Set cookies for web as we'll use the same client
        this.authService.setCookieTokens(res, id_token, access_token, refresh_token);
        return res.redirect(targetUrl);
      }
    } catch (e) {
      this.logger.error(e);
      throw new UnauthorizedException("Auth failed");
    }
  }

  @Put("exchange")
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({
    summary: "Exchange session code for cookies",
    description:
      "This seeds the mobile CookieJar and is only intended to be used with mobile apps. We implement our own PKCE implementation to protect against interception attacks.",
  })
  @ApiResponse({ status: 204, description: "Cookies set successfully" })
  @ApiResponse({ status: 400, description: "Invalid token DTO" })
  async exchange(@Body() dto: MobileTokenExchangeDto, @Req() _req: Request, @Res({ passthrough: true }) res: Response) {
    if (!dto.code) throw new BadRequestException("A valid handoff code is required.");
    if (!dto.appVerifier) throw new BadRequestException("A valid requester key is required.");
    // Grab the tokens based on the code
    const tokens = await this.getMobileHandoff(dto.code);
    // Before setting them, verify the app challenger was who actually requested the exchange.
    const hashedVerifier = createHash("sha256").update(dto.appVerifier).digest("base64url");
    // Compare it to the challenge they gave us at the very beginning
    if (hashedVerifier !== tokens.appChallenge) {
      this.logger.error(
        `CRITICAL SECURITY ALERT: OIDC Token exchange failed due to App Binding mismatch. ` +
          `Potential interception attack detected! The handoff code has been successfully burned to prevent compromise.` +
          `You may have a malicious attacker in between your server and your mobile device!`,
      );
      throw new UnauthorizedException("Invalid app verifier");
    } else {
      // It matched so go ahead and attack cookies
      this.authService.setCookieTokens(res, tokens.idToken, tokens.accessToken, tokens.refreshToken);
    }
  }
}
