name: CI - Tests and Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: ./backend/package.json

      - name: Monitor Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2.3.1
        with:
          working-directory: backend
          test-script: npm test -- --coverage
